import { DM_Sans } from "next/font/google";
import "./globals.scss";

const dmSans = DM_Sans({ subsets: ["latin"], weight: ['100', '300', '400', '500', '700', '900'] });

// Analytics
import { Analytics } from "@vercel/analytics/react"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body className={dmSans.className}>
        {children}
        <Analytics />
      </body>
    </html>
  );
}
